// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twilioconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twilioconnector.proxies.microflows.Microflows;

public class SendSMS_JA extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __SMSParam;
	private twilioconnector.proxies.SMSParam SMSParam;

	public SendSMS_JA(IContext context, IMendixObject SMSParam)
	{
		super(context);
		this.__SMSParam = SMSParam;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.SMSParam = __SMSParam == null ? null : twilioconnector.proxies.SMSParam.initialize(getContext(), __SMSParam);

		// BEGIN USER CODE
		Boolean sendSMS = Microflows.sendSMS(this.getContext(), SMSParam);
		if(sendSMS)
		{
			return true;
		}
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendSMS_JA";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
