// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfamodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MFAmodule module
	public static boolean aSU_MFA(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.ASU_MFA").withParams(params).execute(context);
	}
	/**
	 * Called from JAVA Action
	 */
	public static mfamodule.proxies.MFA dS_MFA_GET(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MFAmodule.DS_MFA_GET").withParams(params).execute(context);
		return result == null ? null : mfamodule.proxies.MFA.initialize(context, result);
	}
	public static boolean sUB_CheckMaxLogin(IContext context, mfamodule.proxies.UserHelper _userHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserHelper", _userHelper == null ? null : _userHelper.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_CheckMaxLogin").withParams(params).execute(context);
	}
	public static boolean sUB_CheckMaxMFA(IContext context, mfamodule.proxies.UserHelper _userHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserHelper", _userHelper == null ? null : _userHelper.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_CheckMaxMFA").withParams(params).execute(context);
	}
	public static mfamodule.proxies.DatadogLog sUB_DatadogLog_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MFAmodule.SUB_DatadogLog_Create").withParams(params).execute(context);
		return result == null ? null : mfamodule.proxies.DatadogLog.initialize(context, result);
	}
	public static void sUB_DatadogLog_Default(IContext context, java.lang.String _eventName, mfamodule.proxies.DatadogOutcome_Enum _eventOutcome, java.lang.String _username, java.lang.String _userId, java.lang.String _eventCatagory, mfamodule.proxies.DatadogLog _datadogLog, java.lang.String _iP)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EventName", _eventName);
		params.put("EventOutcome", _eventOutcome == null ? null : _eventOutcome.name());
		params.put("Username", _username);
		params.put("UserId", _userId);
		params.put("EventCatagory", _eventCatagory);
		params.put("DatadogLog", _datadogLog == null ? null : _datadogLog.getMendixObject());
		params.put("IP", _iP);
		Core.microflowCall("MFAmodule.SUB_DatadogLog_Default").withParams(params).execute(context);
	}
	public static void sUB_DatadogLog_Default_API(IContext context, java.lang.String _eventName, mfamodule.proxies.DatadogOutcome_Enum _eventOutcome, java.lang.String _username, java.lang.String _userId, java.lang.String _uRL, java.lang.String _method, java.lang.String _statusCode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EventName", _eventName);
		params.put("EventOutcome", _eventOutcome == null ? null : _eventOutcome.name());
		params.put("Username", _username);
		params.put("UserId", _userId);
		params.put("URL", _uRL);
		params.put("Method", _method);
		params.put("StatusCode", _statusCode);
		Core.microflowCall("MFAmodule.SUB_DatadogLog_Default_API").withParams(params).execute(context);
	}
	public static void sUB_DatadogLog_WriteLog(IContext context, mfamodule.proxies.DatadogLog _datadogLog)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatadogLog", _datadogLog == null ? null : _datadogLog.getMendixObject());
		Core.microflowCall("MFAmodule.SUB_DatadogLog_WriteLog").withParams(params).execute(context);
	}
	public static void sUB_MFA_Create_Native(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MFAmodule.SUB_MFA_Create_Native").withParams(params).execute(context);
	}
	public static boolean sUB_MFA_CreateCode(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_MFA_CreateCode").withParams(params).execute(context);
	}
	public static mfamodule.proxies.UserHelper sUB_MFA_GetUserHelper(IContext context, mfamodule.proxies.MFA _mFA, java.lang.String _mFAUsername)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		params.put("MFAUsername", _mFAUsername);
		IMendixObject result = (IMendixObject)Core.microflowCall("MFAmodule.SUB_MFA_GetUserHelper").withParams(params).execute(context);
		return result == null ? null : mfamodule.proxies.UserHelper.initialize(context, result);
	}
	/**
	 * Called from JAVA Action
	 */
	public static boolean sUB_MFA_UserDisabledCheck(IContext context, java.lang.String _username)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Username", _username);
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_MFA_UserDisabledCheck").withParams(params).execute(context);
	}
	/**
	 * Called from JAVA Action
	 */
	public static boolean sUB_MFA_Validate(IContext context, mfamodule.proxies.MFA _mFA, java.lang.String _mFAUsername)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		params.put("MFAUsername", _mFAUsername);
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_MFA_Validate").withParams(params).execute(context);
	}
	public static boolean sUB_MFA_ValidateCode(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFAmodule.SUB_MFA_ValidateCode").withParams(params).execute(context);
	}
}
