// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_GenerateNumberRandom(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_GenerateNumberRandom").withParams(params).execute(context);
	}
	public static boolean aSU(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ASU").withParams(params).execute(context);
	}
	public static java.lang.String getTest(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("MyFirstModule.GetTest").withParams(params).execute(context);
	}
	public static boolean sUB_MFA_CreateCode_Log_Test(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.SUB_MFA_CreateCode_Log_Test").withParams(params).execute(context);
	}
	public static boolean sUB_MFA_ValidateCode_LocallyGenerated(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.SUB_MFA_ValidateCode_LocallyGenerated").withParams(params).execute(context);
	}
}