// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies;

public class Helper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleAuthenticator.Helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OTPAuthURL("OTPAuthURL");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GoogleAuthenticator.Helper"));
	}

	protected Helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject)
	{
		if (helperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GoogleAuthenticator.Helper", helperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GoogleAuthenticator.Helper");

		this.helperMendixObject = helperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Helper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googleauthenticator.proxies.Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googleauthenticator.proxies.Helper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static googleauthenticator.proxies.Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googleauthenticator.proxies.Helper(context, mendixObject);
	}

	public static googleauthenticator.proxies.Helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googleauthenticator.proxies.Helper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OTPAuthURL
	 */
	public final java.lang.String getOTPAuthURL()
	{
		return getOTPAuthURL(getContext());
	}

	/**
	 * @param context
	 * @return value of OTPAuthURL
	 */
	public final java.lang.String getOTPAuthURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OTPAuthURL.toString());
	}

	/**
	 * Set value of OTPAuthURL
	 * @param otpauthurl
	 */
	public final void setOTPAuthURL(java.lang.String otpauthurl)
	{
		setOTPAuthURL(getContext(), otpauthurl);
	}

	/**
	 * Set value of OTPAuthURL
	 * @param context
	 * @param otpauthurl
	 */
	public final void setOTPAuthURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String otpauthurl)
	{
		getMendixObject().setValue(context, MemberNames.OTPAuthURL.toString(), otpauthurl);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return helperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googleauthenticator.proxies.Helper that = (googleauthenticator.proxies.Helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GoogleAuthenticator.Helper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
