// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GoogleAuthenticator module

	public static java.lang.Long getDaysBeforeExpiry()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("GoogleAuthenticator.DaysBeforeExpiry");
	}

	public static java.lang.String getIssuerMFA()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GoogleAuthenticator.IssuerMFA");
	}
}