// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfatestmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MFATestModule module
	public static boolean aSU(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MFATestModule.ASU").withParams(params).execute(context);
	}
	public static java.lang.String getTest(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("MFATestModule.GetTest").withParams(params).execute(context);
	}
	public static void getVersion(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MFATestModule.GetVersion").withParams(params).execute(context);
	}
	public static boolean mFA_CreateCode_Log_Test(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFATestModule.MFA_CreateCode_Log_Test").withParams(params).execute(context);
	}
	public static boolean mFA_UserDisabledCheck_Test(IContext context, java.lang.String _username)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Username", _username);
		return (java.lang.Boolean) Core.microflowCall("MFATestModule.MFA_UserDisabledCheck_Test").withParams(params).execute(context);
	}
	public static boolean mFA_ValidateCode_LocallyGenerated_Test(IContext context, mfamodule.proxies.MFA _mFA)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MFA", _mFA == null ? null : _mFA.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MFATestModule.MFA_ValidateCode_LocallyGenerated_Test").withParams(params).execute(context);
	}
	public static void testLog(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MFATestModule.TestLog").withParams(params).execute(context);
	}
}
