// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfamodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MFAmodule module

	public static boolean getEnabledMFA()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("MFAmodule.EnabledMFA");
	}

	public static java.lang.String getLognode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MFAmodule.Lognode");
	}

	/**
	* Maximum of attempts after first user+pass is correct and MFA is validated
	*/
	public static java.lang.Long getMaxAttemptsMFA()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MFAmodule.MaxAttemptsMFA");
	}

	/**
	* Maximum attempts for user+password
	*/
	public static java.lang.Long getMaxLoginAttempts()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MFAmodule.MaxLoginAttempts");
	}

	/**
	* Default Mendix platform is 5 minutes to unblock an user. Must be greater then 5 minutes
	*/
	public static java.lang.Long getUnblockLoginMinutes()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MFAmodule.UnblockLoginMinutes");
	}

	/**
	* Default Mendix platform is 5 minutes to unblock an user
	*/
	public static java.lang.Long getUnblockMFAMinutes()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MFAmodule.UnblockMFAMinutes");
	}
}