// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public class MxObjectMember
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxObjectMemberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxModelReflection.MxObjectMember";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttributeName("AttributeName"),
		AttributeType("AttributeType"),
		AttributeTypeEnum("AttributeTypeEnum"),
		CompleteName("CompleteName"),
		DescriptiveName("DescriptiveName"),
		FieldLength("FieldLength"),
		IsVirtual("IsVirtual"),
		MxObjectMember_MxObjectType("MxModelReflection.MxObjectMember_MxObjectType"),
		MxObjectMember_Type("MxModelReflection.MxObjectMember_Type");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxObjectMemberMendixObject)
	{
		if (mxObjectMemberMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mxObjectMemberMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mxObjectMemberMendixObject = mxObjectMemberMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxObjectMember.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mxmodelreflection.proxies.MxObjectMember initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxmodelreflection.proxies.MxObjectMember.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxmodelreflection.proxies.MxObjectMember initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MxModelReflection.MxObjectEnum", mendixObject.getType())) {
			return mxmodelreflection.proxies.MxObjectEnum.initialize(context, mendixObject);
		}
		return new mxmodelreflection.proxies.MxObjectMember(context, mendixObject);
	}

	public static mxmodelreflection.proxies.MxObjectMember load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxmodelreflection.proxies.MxObjectMember.initialize(context, mendixObject);
	}

	public static java.util.List<? extends mxmodelreflection.proxies.MxObjectMember> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxmodelreflection.proxies.MxObjectMember.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(java.lang.String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * @return value of AttributeType
	 */
	public final java.lang.String getAttributeType()
	{
		return getAttributeType(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeType
	 */
	public final java.lang.String getAttributeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeType.toString());
	}

	/**
	 * Set value of AttributeType
	 * @param attributetype
	 */
	public final void setAttributeType(java.lang.String attributetype)
	{
		setAttributeType(getContext(), attributetype);
	}

	/**
	 * Set value of AttributeType
	 * @param context
	 * @param attributetype
	 */
	public final void setAttributeType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributetype)
	{
		getMendixObject().setValue(context, MemberNames.AttributeType.toString(), attributetype);
	}

	/**
	 * Set value of AttributeTypeEnum
	 * @param attributetypeenum
	 */
	public final mxmodelreflection.proxies.PrimitiveTypes getAttributeTypeEnum()
	{
		return getAttributeTypeEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeTypeEnum
	 */
	public final mxmodelreflection.proxies.PrimitiveTypes getAttributeTypeEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AttributeTypeEnum.toString());
		if (obj == null) {
			return null;
		}
		return mxmodelreflection.proxies.PrimitiveTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AttributeTypeEnum
	 * @param attributetypeenum
	 */
	public final void setAttributeTypeEnum(mxmodelreflection.proxies.PrimitiveTypes attributetypeenum)
	{
		setAttributeTypeEnum(getContext(), attributetypeenum);
	}

	/**
	 * Set value of AttributeTypeEnum
	 * @param context
	 * @param attributetypeenum
	 */
	public final void setAttributeTypeEnum(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.PrimitiveTypes attributetypeenum)
	{
		if (attributetypeenum != null) {
			getMendixObject().setValue(context, MemberNames.AttributeTypeEnum.toString(), attributetypeenum.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AttributeTypeEnum.toString(), null);
		}
	}

	/**
	 * @return value of CompleteName
	 */
	public final java.lang.String getCompleteName()
	{
		return getCompleteName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteName
	 */
	public final java.lang.String getCompleteName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompleteName.toString());
	}

	/**
	 * Set value of CompleteName
	 * @param completename
	 */
	public final void setCompleteName(java.lang.String completename)
	{
		setCompleteName(getContext(), completename);
	}

	/**
	 * Set value of CompleteName
	 * @param context
	 * @param completename
	 */
	public final void setCompleteName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String completename)
	{
		getMendixObject().setValue(context, MemberNames.CompleteName.toString(), completename);
	}

	/**
	 * @return value of DescriptiveName
	 */
	public final java.lang.String getDescriptiveName()
	{
		return getDescriptiveName(getContext());
	}

	/**
	 * @param context
	 * @return value of DescriptiveName
	 */
	public final java.lang.String getDescriptiveName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DescriptiveName.toString());
	}

	/**
	 * Set value of DescriptiveName
	 * @param descriptivename
	 */
	public final void setDescriptiveName(java.lang.String descriptivename)
	{
		setDescriptiveName(getContext(), descriptivename);
	}

	/**
	 * Set value of DescriptiveName
	 * @param context
	 * @param descriptivename
	 */
	public final void setDescriptiveName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descriptivename)
	{
		getMendixObject().setValue(context, MemberNames.DescriptiveName.toString(), descriptivename);
	}

	/**
	 * @return value of FieldLength
	 */
	public final java.lang.Integer getFieldLength()
	{
		return getFieldLength(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldLength
	 */
	public final java.lang.Integer getFieldLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FieldLength.toString());
	}

	/**
	 * Set value of FieldLength
	 * @param fieldlength
	 */
	public final void setFieldLength(java.lang.Integer fieldlength)
	{
		setFieldLength(getContext(), fieldlength);
	}

	/**
	 * Set value of FieldLength
	 * @param context
	 * @param fieldlength
	 */
	public final void setFieldLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer fieldlength)
	{
		getMendixObject().setValue(context, MemberNames.FieldLength.toString(), fieldlength);
	}

	/**
	 * @return value of IsVirtual
	 */
	public final java.lang.Boolean getIsVirtual()
	{
		return getIsVirtual(getContext());
	}

	/**
	 * @param context
	 * @return value of IsVirtual
	 */
	public final java.lang.Boolean getIsVirtual(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsVirtual.toString());
	}

	/**
	 * Set value of IsVirtual
	 * @param isvirtual
	 */
	public final void setIsVirtual(java.lang.Boolean isvirtual)
	{
		setIsVirtual(getContext(), isvirtual);
	}

	/**
	 * Set value of IsVirtual
	 * @param context
	 * @param isvirtual
	 */
	public final void setIsVirtual(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvirtual)
	{
		getMendixObject().setValue(context, MemberNames.IsVirtual.toString(), isvirtual);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxObjectMember_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxObjectMember_MxObjectType() throws com.mendix.core.CoreException
	{
		return getMxObjectMember_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of MxObjectMember_MxObjectType
	 * @throws com.mendix.core.CoreException
	 */
	public final mxmodelreflection.proxies.MxObjectType getMxObjectMember_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxObjectMember_MxObjectType.toString());
		if (identifier != null) {
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxObjectMember_MxObjectType
	 * @param mxobjectmember_mxobjecttype
	 */
	public final void setMxObjectMember_MxObjectType(mxmodelreflection.proxies.MxObjectType mxobjectmember_mxobjecttype)
	{
		setMxObjectMember_MxObjectType(getContext(), mxobjectmember_mxobjecttype);
	}

	/**
	 * Set value of MxObjectMember_MxObjectType
	 * @param context
	 * @param mxobjectmember_mxobjecttype
	 */
	public final void setMxObjectMember_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType mxobjectmember_mxobjecttype)
	{
		if (mxobjectmember_mxobjecttype == null) {
			getMendixObject().setValue(context, MemberNames.MxObjectMember_MxObjectType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxObjectMember_MxObjectType.toString(), mxobjectmember_mxobjecttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MxObjectMember_Type
	 */
	public final mxmodelreflection.proxies.ValueType getMxObjectMember_Type() throws com.mendix.core.CoreException
	{
		return getMxObjectMember_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of MxObjectMember_Type
	 * @throws com.mendix.core.CoreException
	 */
	public final mxmodelreflection.proxies.ValueType getMxObjectMember_Type(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.ValueType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxObjectMember_Type.toString());
		if (identifier != null) {
			result = mxmodelreflection.proxies.ValueType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MxObjectMember_Type
	 * @param mxobjectmember_type
	 */
	public final void setMxObjectMember_Type(mxmodelreflection.proxies.ValueType mxobjectmember_type)
	{
		setMxObjectMember_Type(getContext(), mxobjectmember_type);
	}

	/**
	 * Set value of MxObjectMember_Type
	 * @param context
	 * @param mxobjectmember_type
	 */
	public final void setMxObjectMember_Type(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.ValueType mxobjectmember_type)
	{
		if (mxobjectmember_type == null) {
			getMendixObject().setValue(context, MemberNames.MxObjectMember_Type.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MxObjectMember_Type.toString(), mxobjectmember_type.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxObjectMemberMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxmodelreflection.proxies.MxObjectMember that = (mxmodelreflection.proxies.MxObjectMember) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
