// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approntocommon.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ApprontoCommon module

	/**
	* DEV, TST, ACCP, PRD
	*/
	public static java.lang.String getEnvironment()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ApprontoCommon.Environment");
	}
}