// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfamodule.proxies;

public class DatadogLog
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject datadogLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MFAmodule.DatadogLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		evt_category("evt_category"),
		evt_name("evt_name"),
		evt_outcome("evt_outcome"),
		usr_name("usr_name"),
		usr_id("usr_id"),
		network_client_ip("network_client_ip"),
		country_iso__code("country_iso__code"),
		http_method("http_method"),
		http_useragent("http_useragent"),
		http_url("http_url"),
		http_status__code("http_status__code"),
		DatadogLog_MFA("MFAmodule.DatadogLog_MFA");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DatadogLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DatadogLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject datadogLogMendixObject)
	{
		if (datadogLogMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, datadogLogMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.datadogLogMendixObject = datadogLogMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DatadogLog.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mfamodule.proxies.DatadogLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mfamodule.proxies.DatadogLog.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mfamodule.proxies.DatadogLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mfamodule.proxies.DatadogLog(context, mendixObject);
	}

	public static mfamodule.proxies.DatadogLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mfamodule.proxies.DatadogLog.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of evt_category
	 */
	public final java.lang.String getevt_category()
	{
		return getevt_category(getContext());
	}

	/**
	 * @param context
	 * @return value of evt_category
	 */
	public final java.lang.String getevt_category(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.evt_category.toString());
	}

	/**
	 * Set value of evt_category
	 * @param evt_category
	 */
	public final void setevt_category(java.lang.String evt_category)
	{
		setevt_category(getContext(), evt_category);
	}

	/**
	 * Set value of evt_category
	 * @param context
	 * @param evt_category
	 */
	public final void setevt_category(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String evt_category)
	{
		getMendixObject().setValue(context, MemberNames.evt_category.toString(), evt_category);
	}

	/**
	 * @return value of evt_name
	 */
	public final java.lang.String getevt_name()
	{
		return getevt_name(getContext());
	}

	/**
	 * @param context
	 * @return value of evt_name
	 */
	public final java.lang.String getevt_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.evt_name.toString());
	}

	/**
	 * Set value of evt_name
	 * @param evt_name
	 */
	public final void setevt_name(java.lang.String evt_name)
	{
		setevt_name(getContext(), evt_name);
	}

	/**
	 * Set value of evt_name
	 * @param context
	 * @param evt_name
	 */
	public final void setevt_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String evt_name)
	{
		getMendixObject().setValue(context, MemberNames.evt_name.toString(), evt_name);
	}

	/**
	 * Set value of evt_outcome
	 * @param evt_outcome
	 */
	public final mfamodule.proxies.DatadogOutcome_Enum getevt_outcome()
	{
		return getevt_outcome(getContext());
	}

	/**
	 * @param context
	 * @return value of evt_outcome
	 */
	public final mfamodule.proxies.DatadogOutcome_Enum getevt_outcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.evt_outcome.toString());
		if (obj == null) {
			return null;
		}
		return mfamodule.proxies.DatadogOutcome_Enum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of evt_outcome
	 * @param evt_outcome
	 */
	public final void setevt_outcome(mfamodule.proxies.DatadogOutcome_Enum evt_outcome)
	{
		setevt_outcome(getContext(), evt_outcome);
	}

	/**
	 * Set value of evt_outcome
	 * @param context
	 * @param evt_outcome
	 */
	public final void setevt_outcome(com.mendix.systemwideinterfaces.core.IContext context, mfamodule.proxies.DatadogOutcome_Enum evt_outcome)
	{
		if (evt_outcome != null) {
			getMendixObject().setValue(context, MemberNames.evt_outcome.toString(), evt_outcome.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.evt_outcome.toString(), null);
		}
	}

	/**
	 * @return value of usr_name
	 */
	public final java.lang.String getusr_name()
	{
		return getusr_name(getContext());
	}

	/**
	 * @param context
	 * @return value of usr_name
	 */
	public final java.lang.String getusr_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.usr_name.toString());
	}

	/**
	 * Set value of usr_name
	 * @param usr_name
	 */
	public final void setusr_name(java.lang.String usr_name)
	{
		setusr_name(getContext(), usr_name);
	}

	/**
	 * Set value of usr_name
	 * @param context
	 * @param usr_name
	 */
	public final void setusr_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usr_name)
	{
		getMendixObject().setValue(context, MemberNames.usr_name.toString(), usr_name);
	}

	/**
	 * @return value of usr_id
	 */
	public final java.lang.String getusr_id()
	{
		return getusr_id(getContext());
	}

	/**
	 * @param context
	 * @return value of usr_id
	 */
	public final java.lang.String getusr_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.usr_id.toString());
	}

	/**
	 * Set value of usr_id
	 * @param usr_id
	 */
	public final void setusr_id(java.lang.String usr_id)
	{
		setusr_id(getContext(), usr_id);
	}

	/**
	 * Set value of usr_id
	 * @param context
	 * @param usr_id
	 */
	public final void setusr_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usr_id)
	{
		getMendixObject().setValue(context, MemberNames.usr_id.toString(), usr_id);
	}

	/**
	 * @return value of network_client_ip
	 */
	public final java.lang.String getnetwork_client_ip()
	{
		return getnetwork_client_ip(getContext());
	}

	/**
	 * @param context
	 * @return value of network_client_ip
	 */
	public final java.lang.String getnetwork_client_ip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.network_client_ip.toString());
	}

	/**
	 * Set value of network_client_ip
	 * @param network_client_ip
	 */
	public final void setnetwork_client_ip(java.lang.String network_client_ip)
	{
		setnetwork_client_ip(getContext(), network_client_ip);
	}

	/**
	 * Set value of network_client_ip
	 * @param context
	 * @param network_client_ip
	 */
	public final void setnetwork_client_ip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String network_client_ip)
	{
		getMendixObject().setValue(context, MemberNames.network_client_ip.toString(), network_client_ip);
	}

	/**
	 * @return value of country_iso__code
	 */
	public final java.lang.String getcountry_iso__code()
	{
		return getcountry_iso__code(getContext());
	}

	/**
	 * @param context
	 * @return value of country_iso__code
	 */
	public final java.lang.String getcountry_iso__code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.country_iso__code.toString());
	}

	/**
	 * Set value of country_iso__code
	 * @param country_iso__code
	 */
	public final void setcountry_iso__code(java.lang.String country_iso__code)
	{
		setcountry_iso__code(getContext(), country_iso__code);
	}

	/**
	 * Set value of country_iso__code
	 * @param context
	 * @param country_iso__code
	 */
	public final void setcountry_iso__code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country_iso__code)
	{
		getMendixObject().setValue(context, MemberNames.country_iso__code.toString(), country_iso__code);
	}

	/**
	 * @return value of http_method
	 */
	public final java.lang.String gethttp_method()
	{
		return gethttp_method(getContext());
	}

	/**
	 * @param context
	 * @return value of http_method
	 */
	public final java.lang.String gethttp_method(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.http_method.toString());
	}

	/**
	 * Set value of http_method
	 * @param http_method
	 */
	public final void sethttp_method(java.lang.String http_method)
	{
		sethttp_method(getContext(), http_method);
	}

	/**
	 * Set value of http_method
	 * @param context
	 * @param http_method
	 */
	public final void sethttp_method(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String http_method)
	{
		getMendixObject().setValue(context, MemberNames.http_method.toString(), http_method);
	}

	/**
	 * @return value of http_useragent
	 */
	public final java.lang.String gethttp_useragent()
	{
		return gethttp_useragent(getContext());
	}

	/**
	 * @param context
	 * @return value of http_useragent
	 */
	public final java.lang.String gethttp_useragent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.http_useragent.toString());
	}

	/**
	 * Set value of http_useragent
	 * @param http_useragent
	 */
	public final void sethttp_useragent(java.lang.String http_useragent)
	{
		sethttp_useragent(getContext(), http_useragent);
	}

	/**
	 * Set value of http_useragent
	 * @param context
	 * @param http_useragent
	 */
	public final void sethttp_useragent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String http_useragent)
	{
		getMendixObject().setValue(context, MemberNames.http_useragent.toString(), http_useragent);
	}

	/**
	 * @return value of http_url
	 */
	public final java.lang.String gethttp_url()
	{
		return gethttp_url(getContext());
	}

	/**
	 * @param context
	 * @return value of http_url
	 */
	public final java.lang.String gethttp_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.http_url.toString());
	}

	/**
	 * Set value of http_url
	 * @param http_url
	 */
	public final void sethttp_url(java.lang.String http_url)
	{
		sethttp_url(getContext(), http_url);
	}

	/**
	 * Set value of http_url
	 * @param context
	 * @param http_url
	 */
	public final void sethttp_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String http_url)
	{
		getMendixObject().setValue(context, MemberNames.http_url.toString(), http_url);
	}

	/**
	 * @return value of http_status__code
	 */
	public final java.lang.String gethttp_status__code()
	{
		return gethttp_status__code(getContext());
	}

	/**
	 * @param context
	 * @return value of http_status__code
	 */
	public final java.lang.String gethttp_status__code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.http_status__code.toString());
	}

	/**
	 * Set value of http_status__code
	 * @param http_status__code
	 */
	public final void sethttp_status__code(java.lang.String http_status__code)
	{
		sethttp_status__code(getContext(), http_status__code);
	}

	/**
	 * Set value of http_status__code
	 * @param context
	 * @param http_status__code
	 */
	public final void sethttp_status__code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String http_status__code)
	{
		getMendixObject().setValue(context, MemberNames.http_status__code.toString(), http_status__code);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DatadogLog_MFA
	 */
	public final mfamodule.proxies.MFA getDatadogLog_MFA() throws com.mendix.core.CoreException
	{
		return getDatadogLog_MFA(getContext());
	}

	/**
	 * @param context
	 * @return value of DatadogLog_MFA
	 * @throws com.mendix.core.CoreException
	 */
	public final mfamodule.proxies.MFA getDatadogLog_MFA(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mfamodule.proxies.MFA result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DatadogLog_MFA.toString());
		if (identifier != null) {
			result = mfamodule.proxies.MFA.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DatadogLog_MFA
	 * @param datadoglog_mfa
	 */
	public final void setDatadogLog_MFA(mfamodule.proxies.MFA datadoglog_mfa)
	{
		setDatadogLog_MFA(getContext(), datadoglog_mfa);
	}

	/**
	 * Set value of DatadogLog_MFA
	 * @param context
	 * @param datadoglog_mfa
	 */
	public final void setDatadogLog_MFA(com.mendix.systemwideinterfaces.core.IContext context, mfamodule.proxies.MFA datadoglog_mfa)
	{
		if (datadoglog_mfa == null) {
			getMendixObject().setValue(context, MemberNames.DatadogLog_MFA.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DatadogLog_MFA.toString(), datadoglog_mfa.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return datadogLogMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mfamodule.proxies.DatadogLog that = (mfamodule.proxies.DatadogLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
