// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfamodule.proxies;

public class SessionData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sessionDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MFAmodule.SessionData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Csrftoken("Csrftoken"),
		SessionObjectId("SessionObjectId"),
		CookieHeader("CookieHeader"),
		JSON("JSON");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SessionData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SessionData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sessionDataMendixObject)
	{
		if (sessionDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sessionDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sessionDataMendixObject = sessionDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SessionData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mfamodule.proxies.SessionData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mfamodule.proxies.SessionData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mfamodule.proxies.SessionData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mfamodule.proxies.SessionData(context, mendixObject);
	}

	public static mfamodule.proxies.SessionData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mfamodule.proxies.SessionData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Csrftoken
	 */
	public final java.lang.String getCsrftoken()
	{
		return getCsrftoken(getContext());
	}

	/**
	 * @param context
	 * @return value of Csrftoken
	 */
	public final java.lang.String getCsrftoken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Csrftoken.toString());
	}

	/**
	 * Set value of Csrftoken
	 * @param csrftoken
	 */
	public final void setCsrftoken(java.lang.String csrftoken)
	{
		setCsrftoken(getContext(), csrftoken);
	}

	/**
	 * Set value of Csrftoken
	 * @param context
	 * @param csrftoken
	 */
	public final void setCsrftoken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csrftoken)
	{
		getMendixObject().setValue(context, MemberNames.Csrftoken.toString(), csrftoken);
	}

	/**
	 * @return value of SessionObjectId
	 */
	public final java.lang.String getSessionObjectId()
	{
		return getSessionObjectId(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionObjectId
	 */
	public final java.lang.String getSessionObjectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SessionObjectId.toString());
	}

	/**
	 * Set value of SessionObjectId
	 * @param sessionobjectid
	 */
	public final void setSessionObjectId(java.lang.String sessionobjectid)
	{
		setSessionObjectId(getContext(), sessionobjectid);
	}

	/**
	 * Set value of SessionObjectId
	 * @param context
	 * @param sessionobjectid
	 */
	public final void setSessionObjectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sessionobjectid)
	{
		getMendixObject().setValue(context, MemberNames.SessionObjectId.toString(), sessionobjectid);
	}

	/**
	 * @return value of CookieHeader
	 */
	public final java.lang.String getCookieHeader()
	{
		return getCookieHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of CookieHeader
	 */
	public final java.lang.String getCookieHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CookieHeader.toString());
	}

	/**
	 * Set value of CookieHeader
	 * @param cookieheader
	 */
	public final void setCookieHeader(java.lang.String cookieheader)
	{
		setCookieHeader(getContext(), cookieheader);
	}

	/**
	 * Set value of CookieHeader
	 * @param context
	 * @param cookieheader
	 */
	public final void setCookieHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cookieheader)
	{
		getMendixObject().setValue(context, MemberNames.CookieHeader.toString(), cookieheader);
	}

	/**
	 * @return value of JSON
	 */
	public final java.lang.String getJSON()
	{
		return getJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of JSON
	 */
	public final java.lang.String getJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JSON.toString());
	}

	/**
	 * Set value of JSON
	 * @param json
	 */
	public final void setJSON(java.lang.String json)
	{
		setJSON(getContext(), json);
	}

	/**
	 * Set value of JSON
	 * @param context
	 * @param json
	 */
	public final void setJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String json)
	{
		getMendixObject().setValue(context, MemberNames.JSON.toString(), json);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sessionDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mfamodule.proxies.SessionData that = (mfamodule.proxies.SessionData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
