// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mfamodule.proxies;

public class UserHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MFAmodule.UserHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttemptsLogin("AttemptsLogin"),
		BlockedSinceForMaxLogin("BlockedSinceForMaxLogin"),
		AttemptsMFA("AttemptsMFA"),
		BlockedSinceForMaxMFA("BlockedSinceForMaxMFA"),
		UserHelper_User("MFAmodule.UserHelper_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MFAmodule.UserHelper"));
	}

	protected UserHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userHelperMendixObject)
	{
		if (userHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MFAmodule.UserHelper", userHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MFAmodule.UserHelper");

		this.userHelperMendixObject = userHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mfamodule.proxies.UserHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mfamodule.proxies.UserHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mfamodule.proxies.UserHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mfamodule.proxies.UserHelper(context, mendixObject);
	}

	public static mfamodule.proxies.UserHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mfamodule.proxies.UserHelper.initialize(context, mendixObject);
	}

	public static java.util.List<mfamodule.proxies.UserHelper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mfamodule.proxies.UserHelper> result = new java.util.ArrayList<mfamodule.proxies.UserHelper>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MFAmodule.UserHelper" + xpathConstraint))
			result.add(mfamodule.proxies.UserHelper.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AttemptsLogin
	 */
	public final java.lang.Integer getAttemptsLogin()
	{
		return getAttemptsLogin(getContext());
	}

	/**
	 * @param context
	 * @return value of AttemptsLogin
	 */
	public final java.lang.Integer getAttemptsLogin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AttemptsLogin.toString());
	}

	/**
	 * Set value of AttemptsLogin
	 * @param attemptslogin
	 */
	public final void setAttemptsLogin(java.lang.Integer attemptslogin)
	{
		setAttemptsLogin(getContext(), attemptslogin);
	}

	/**
	 * Set value of AttemptsLogin
	 * @param context
	 * @param attemptslogin
	 */
	public final void setAttemptsLogin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attemptslogin)
	{
		getMendixObject().setValue(context, MemberNames.AttemptsLogin.toString(), attemptslogin);
	}

	/**
	 * @return value of BlockedSinceForMaxLogin
	 */
	public final java.util.Date getBlockedSinceForMaxLogin()
	{
		return getBlockedSinceForMaxLogin(getContext());
	}

	/**
	 * @param context
	 * @return value of BlockedSinceForMaxLogin
	 */
	public final java.util.Date getBlockedSinceForMaxLogin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BlockedSinceForMaxLogin.toString());
	}

	/**
	 * Set value of BlockedSinceForMaxLogin
	 * @param blockedsinceformaxlogin
	 */
	public final void setBlockedSinceForMaxLogin(java.util.Date blockedsinceformaxlogin)
	{
		setBlockedSinceForMaxLogin(getContext(), blockedsinceformaxlogin);
	}

	/**
	 * Set value of BlockedSinceForMaxLogin
	 * @param context
	 * @param blockedsinceformaxlogin
	 */
	public final void setBlockedSinceForMaxLogin(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date blockedsinceformaxlogin)
	{
		getMendixObject().setValue(context, MemberNames.BlockedSinceForMaxLogin.toString(), blockedsinceformaxlogin);
	}

	/**
	 * @return value of AttemptsMFA
	 */
	public final java.lang.Integer getAttemptsMFA()
	{
		return getAttemptsMFA(getContext());
	}

	/**
	 * @param context
	 * @return value of AttemptsMFA
	 */
	public final java.lang.Integer getAttemptsMFA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AttemptsMFA.toString());
	}

	/**
	 * Set value of AttemptsMFA
	 * @param attemptsmfa
	 */
	public final void setAttemptsMFA(java.lang.Integer attemptsmfa)
	{
		setAttemptsMFA(getContext(), attemptsmfa);
	}

	/**
	 * Set value of AttemptsMFA
	 * @param context
	 * @param attemptsmfa
	 */
	public final void setAttemptsMFA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attemptsmfa)
	{
		getMendixObject().setValue(context, MemberNames.AttemptsMFA.toString(), attemptsmfa);
	}

	/**
	 * @return value of BlockedSinceForMaxMFA
	 */
	public final java.util.Date getBlockedSinceForMaxMFA()
	{
		return getBlockedSinceForMaxMFA(getContext());
	}

	/**
	 * @param context
	 * @return value of BlockedSinceForMaxMFA
	 */
	public final java.util.Date getBlockedSinceForMaxMFA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BlockedSinceForMaxMFA.toString());
	}

	/**
	 * Set value of BlockedSinceForMaxMFA
	 * @param blockedsinceformaxmfa
	 */
	public final void setBlockedSinceForMaxMFA(java.util.Date blockedsinceformaxmfa)
	{
		setBlockedSinceForMaxMFA(getContext(), blockedsinceformaxmfa);
	}

	/**
	 * Set value of BlockedSinceForMaxMFA
	 * @param context
	 * @param blockedsinceformaxmfa
	 */
	public final void setBlockedSinceForMaxMFA(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date blockedsinceformaxmfa)
	{
		getMendixObject().setValue(context, MemberNames.BlockedSinceForMaxMFA.toString(), blockedsinceformaxmfa);
	}

	/**
	 * @return value of UserHelper_User
	 */
	public final system.proxies.User getUserHelper_User() throws com.mendix.core.CoreException
	{
		return getUserHelper_User(getContext());
	}

	/**
	 * @param context
	 * @return value of UserHelper_User
	 */
	public final system.proxies.User getUserHelper_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserHelper_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserHelper_User
	 * @param userhelper_user
	 */
	public final void setUserHelper_User(system.proxies.User userhelper_user)
	{
		setUserHelper_User(getContext(), userhelper_user);
	}

	/**
	 * Set value of UserHelper_User
	 * @param context
	 * @param userhelper_user
	 */
	public final void setUserHelper_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User userhelper_user)
	{
		if (userhelper_user == null)
			getMendixObject().setValue(context, MemberNames.UserHelper_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserHelper_User.toString(), userhelper_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mfamodule.proxies.UserHelper that = (mfamodule.proxies.UserHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MFAmodule.UserHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
