// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies;

public class Credential
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject credentialMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwilioConnector.Credential";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		AccountSid("AccountSid"),
		Token("Token"),
		FromPhoneNumber("FromPhoneNumber"),
		CallbackUri("CallbackUri");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Credential(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwilioConnector.Credential"));
	}

	protected Credential(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject credentialMendixObject)
	{
		if (credentialMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwilioConnector.Credential", credentialMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwilioConnector.Credential");

		this.credentialMendixObject = credentialMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Credential.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twilioconnector.proxies.Credential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilioconnector.proxies.Credential.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twilioconnector.proxies.Credential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilioconnector.proxies.Credential(context, mendixObject);
	}

	public static twilioconnector.proxies.Credential load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilioconnector.proxies.Credential.initialize(context, mendixObject);
	}

	public static java.util.List<twilioconnector.proxies.Credential> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<twilioconnector.proxies.Credential> result = new java.util.ArrayList<twilioconnector.proxies.Credential>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TwilioConnector.Credential" + xpathConstraint))
			result.add(twilioconnector.proxies.Credential.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of AccountSid
	 */
	public final java.lang.String getAccountSid()
	{
		return getAccountSid(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountSid
	 */
	public final java.lang.String getAccountSid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountSid.toString());
	}

	/**
	 * Set value of AccountSid
	 * @param accountsid
	 */
	public final void setAccountSid(java.lang.String accountsid)
	{
		setAccountSid(getContext(), accountsid);
	}

	/**
	 * Set value of AccountSid
	 * @param context
	 * @param accountsid
	 */
	public final void setAccountSid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountsid)
	{
		getMendixObject().setValue(context, MemberNames.AccountSid.toString(), accountsid);
	}

	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of FromPhoneNumber
	 */
	public final java.lang.String getFromPhoneNumber()
	{
		return getFromPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of FromPhoneNumber
	 */
	public final java.lang.String getFromPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromPhoneNumber.toString());
	}

	/**
	 * Set value of FromPhoneNumber
	 * @param fromphonenumber
	 */
	public final void setFromPhoneNumber(java.lang.String fromphonenumber)
	{
		setFromPhoneNumber(getContext(), fromphonenumber);
	}

	/**
	 * Set value of FromPhoneNumber
	 * @param context
	 * @param fromphonenumber
	 */
	public final void setFromPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromphonenumber)
	{
		getMendixObject().setValue(context, MemberNames.FromPhoneNumber.toString(), fromphonenumber);
	}

	/**
	 * @return value of CallbackUri
	 */
	public final java.lang.String getCallbackUri()
	{
		return getCallbackUri(getContext());
	}

	/**
	 * @param context
	 * @return value of CallbackUri
	 */
	public final java.lang.String getCallbackUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CallbackUri.toString());
	}

	/**
	 * Set value of CallbackUri
	 * @param callbackuri
	 */
	public final void setCallbackUri(java.lang.String callbackuri)
	{
		setCallbackUri(getContext(), callbackuri);
	}

	/**
	 * Set value of CallbackUri
	 * @param context
	 * @param callbackuri
	 */
	public final void setCallbackUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String callbackuri)
	{
		getMendixObject().setValue(context, MemberNames.CallbackUri.toString(), callbackuri);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return credentialMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilioconnector.proxies.Credential that = (twilioconnector.proxies.Credential) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwilioConnector.Credential";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
