// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies;

public class RootSMSResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootSMSResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwilioConnector.RootSMSResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sid("Sid"),
		Date_created("Date_created"),
		Date_updated("Date_updated"),
		Account_sid("Account_sid"),
		To("To"),
		From("From"),
		Body("Body"),
		Status("Status"),
		Num_segments("Num_segments"),
		Num_media("Num_media"),
		Direction("Direction"),
		Api_version("Api_version"),
		Price_unit("Price_unit"),
		Uri("Uri"),
		Subresource_uris_RootSMSResponse("TwilioConnector.Subresource_uris_RootSMSResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwilioConnector.RootSMSResponse"));
	}

	protected RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootSMSResponseMendixObject)
	{
		if (rootSMSResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwilioConnector.RootSMSResponse", rootSMSResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwilioConnector.RootSMSResponse");

		this.rootSMSResponseMendixObject = rootSMSResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RootSMSResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twilioconnector.proxies.RootSMSResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilioconnector.proxies.RootSMSResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twilioconnector.proxies.RootSMSResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilioconnector.proxies.RootSMSResponse(context, mendixObject);
	}

	public static twilioconnector.proxies.RootSMSResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilioconnector.proxies.RootSMSResponse.initialize(context, mendixObject);
	}

	public static java.util.List<twilioconnector.proxies.RootSMSResponse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<twilioconnector.proxies.RootSMSResponse> result = new java.util.ArrayList<twilioconnector.proxies.RootSMSResponse>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TwilioConnector.RootSMSResponse" + xpathConstraint))
			result.add(twilioconnector.proxies.RootSMSResponse.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sid
	 */
	public final java.lang.String getSid()
	{
		return getSid(getContext());
	}

	/**
	 * @param context
	 * @return value of Sid
	 */
	public final java.lang.String getSid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sid.toString());
	}

	/**
	 * Set value of Sid
	 * @param sid
	 */
	public final void setSid(java.lang.String sid)
	{
		setSid(getContext(), sid);
	}

	/**
	 * Set value of Sid
	 * @param context
	 * @param sid
	 */
	public final void setSid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sid)
	{
		getMendixObject().setValue(context, MemberNames.Sid.toString(), sid);
	}

	/**
	 * @return value of Date_created
	 */
	public final java.lang.String getDate_created()
	{
		return getDate_created(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_created
	 */
	public final java.lang.String getDate_created(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Date_created.toString());
	}

	/**
	 * Set value of Date_created
	 * @param date_created
	 */
	public final void setDate_created(java.lang.String date_created)
	{
		setDate_created(getContext(), date_created);
	}

	/**
	 * Set value of Date_created
	 * @param context
	 * @param date_created
	 */
	public final void setDate_created(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String date_created)
	{
		getMendixObject().setValue(context, MemberNames.Date_created.toString(), date_created);
	}

	/**
	 * @return value of Date_updated
	 */
	public final java.lang.String getDate_updated()
	{
		return getDate_updated(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_updated
	 */
	public final java.lang.String getDate_updated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Date_updated.toString());
	}

	/**
	 * Set value of Date_updated
	 * @param date_updated
	 */
	public final void setDate_updated(java.lang.String date_updated)
	{
		setDate_updated(getContext(), date_updated);
	}

	/**
	 * Set value of Date_updated
	 * @param context
	 * @param date_updated
	 */
	public final void setDate_updated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String date_updated)
	{
		getMendixObject().setValue(context, MemberNames.Date_updated.toString(), date_updated);
	}

	/**
	 * @return value of Account_sid
	 */
	public final java.lang.String getAccount_sid()
	{
		return getAccount_sid(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_sid
	 */
	public final java.lang.String getAccount_sid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account_sid.toString());
	}

	/**
	 * Set value of Account_sid
	 * @param account_sid
	 */
	public final void setAccount_sid(java.lang.String account_sid)
	{
		setAccount_sid(getContext(), account_sid);
	}

	/**
	 * Set value of Account_sid
	 * @param context
	 * @param account_sid
	 */
	public final void setAccount_sid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account_sid)
	{
		getMendixObject().setValue(context, MemberNames.Account_sid.toString(), account_sid);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of From
	 */
	public final java.lang.String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Num_segments
	 */
	public final java.lang.Integer getNum_segments()
	{
		return getNum_segments(getContext());
	}

	/**
	 * @param context
	 * @return value of Num_segments
	 */
	public final java.lang.Integer getNum_segments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Num_segments.toString());
	}

	/**
	 * Set value of Num_segments
	 * @param num_segments
	 */
	public final void setNum_segments(java.lang.Integer num_segments)
	{
		setNum_segments(getContext(), num_segments);
	}

	/**
	 * Set value of Num_segments
	 * @param context
	 * @param num_segments
	 */
	public final void setNum_segments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer num_segments)
	{
		getMendixObject().setValue(context, MemberNames.Num_segments.toString(), num_segments);
	}

	/**
	 * @return value of Num_media
	 */
	public final java.lang.Integer getNum_media()
	{
		return getNum_media(getContext());
	}

	/**
	 * @param context
	 * @return value of Num_media
	 */
	public final java.lang.Integer getNum_media(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Num_media.toString());
	}

	/**
	 * Set value of Num_media
	 * @param num_media
	 */
	public final void setNum_media(java.lang.Integer num_media)
	{
		setNum_media(getContext(), num_media);
	}

	/**
	 * Set value of Num_media
	 * @param context
	 * @param num_media
	 */
	public final void setNum_media(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer num_media)
	{
		getMendixObject().setValue(context, MemberNames.Num_media.toString(), num_media);
	}

	/**
	 * @return value of Direction
	 */
	public final java.lang.String getDirection()
	{
		return getDirection(getContext());
	}

	/**
	 * @param context
	 * @return value of Direction
	 */
	public final java.lang.String getDirection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Direction.toString());
	}

	/**
	 * Set value of Direction
	 * @param direction
	 */
	public final void setDirection(java.lang.String direction)
	{
		setDirection(getContext(), direction);
	}

	/**
	 * Set value of Direction
	 * @param context
	 * @param direction
	 */
	public final void setDirection(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String direction)
	{
		getMendixObject().setValue(context, MemberNames.Direction.toString(), direction);
	}

	/**
	 * @return value of Api_version
	 */
	public final java.lang.String getApi_version()
	{
		return getApi_version(getContext());
	}

	/**
	 * @param context
	 * @return value of Api_version
	 */
	public final java.lang.String getApi_version(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Api_version.toString());
	}

	/**
	 * Set value of Api_version
	 * @param api_version
	 */
	public final void setApi_version(java.lang.String api_version)
	{
		setApi_version(getContext(), api_version);
	}

	/**
	 * Set value of Api_version
	 * @param context
	 * @param api_version
	 */
	public final void setApi_version(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String api_version)
	{
		getMendixObject().setValue(context, MemberNames.Api_version.toString(), api_version);
	}

	/**
	 * @return value of Price_unit
	 */
	public final java.lang.String getPrice_unit()
	{
		return getPrice_unit(getContext());
	}

	/**
	 * @param context
	 * @return value of Price_unit
	 */
	public final java.lang.String getPrice_unit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Price_unit.toString());
	}

	/**
	 * Set value of Price_unit
	 * @param price_unit
	 */
	public final void setPrice_unit(java.lang.String price_unit)
	{
		setPrice_unit(getContext(), price_unit);
	}

	/**
	 * Set value of Price_unit
	 * @param context
	 * @param price_unit
	 */
	public final void setPrice_unit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String price_unit)
	{
		getMendixObject().setValue(context, MemberNames.Price_unit.toString(), price_unit);
	}

	/**
	 * @return value of Uri
	 */
	public final java.lang.String getUri()
	{
		return getUri(getContext());
	}

	/**
	 * @param context
	 * @return value of Uri
	 */
	public final java.lang.String getUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Uri.toString());
	}

	/**
	 * Set value of Uri
	 * @param uri
	 */
	public final void setUri(java.lang.String uri)
	{
		setUri(getContext(), uri);
	}

	/**
	 * Set value of Uri
	 * @param context
	 * @param uri
	 */
	public final void setUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uri)
	{
		getMendixObject().setValue(context, MemberNames.Uri.toString(), uri);
	}

	/**
	 * @return value of Subresource_uris_RootSMSResponse
	 */
	public final twilioconnector.proxies.Subresource_uris getSubresource_uris_RootSMSResponse() throws com.mendix.core.CoreException
	{
		return getSubresource_uris_RootSMSResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Subresource_uris_RootSMSResponse
	 */
	public final twilioconnector.proxies.Subresource_uris getSubresource_uris_RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twilioconnector.proxies.Subresource_uris result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString());
		if (identifier != null)
			result = twilioconnector.proxies.Subresource_uris.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Subresource_uris_RootSMSResponse
	 * @param subresource_uris_rootsmsresponse
	 */
	public final void setSubresource_uris_RootSMSResponse(twilioconnector.proxies.Subresource_uris subresource_uris_rootsmsresponse)
	{
		setSubresource_uris_RootSMSResponse(getContext(), subresource_uris_rootsmsresponse);
	}

	/**
	 * Set value of Subresource_uris_RootSMSResponse
	 * @param context
	 * @param subresource_uris_rootsmsresponse
	 */
	public final void setSubresource_uris_RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context, twilioconnector.proxies.Subresource_uris subresource_uris_rootsmsresponse)
	{
		if (subresource_uris_rootsmsresponse == null)
			getMendixObject().setValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString(), subresource_uris_rootsmsresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootSMSResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilioconnector.proxies.RootSMSResponse that = (twilioconnector.proxies.RootSMSResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwilioConnector.RootSMSResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
