// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies;

public class SMSParam
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sMSParamMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwilioConnector.SMSParam";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CredentialName("CredentialName"),
		DestinationNumber("DestinationNumber"),
		Message("Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SMSParam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwilioConnector.SMSParam"));
	}

	protected SMSParam(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sMSParamMendixObject)
	{
		if (sMSParamMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwilioConnector.SMSParam", sMSParamMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwilioConnector.SMSParam");

		this.sMSParamMendixObject = sMSParamMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SMSParam.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twilioconnector.proxies.SMSParam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilioconnector.proxies.SMSParam.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twilioconnector.proxies.SMSParam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilioconnector.proxies.SMSParam(context, mendixObject);
	}

	public static twilioconnector.proxies.SMSParam load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilioconnector.proxies.SMSParam.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CredentialName
	 */
	public final java.lang.String getCredentialName()
	{
		return getCredentialName(getContext());
	}

	/**
	 * @param context
	 * @return value of CredentialName
	 */
	public final java.lang.String getCredentialName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CredentialName.toString());
	}

	/**
	 * Set value of CredentialName
	 * @param credentialname
	 */
	public final void setCredentialName(java.lang.String credentialname)
	{
		setCredentialName(getContext(), credentialname);
	}

	/**
	 * Set value of CredentialName
	 * @param context
	 * @param credentialname
	 */
	public final void setCredentialName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String credentialname)
	{
		getMendixObject().setValue(context, MemberNames.CredentialName.toString(), credentialname);
	}

	/**
	 * @return value of DestinationNumber
	 */
	public final java.lang.String getDestinationNumber()
	{
		return getDestinationNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of DestinationNumber
	 */
	public final java.lang.String getDestinationNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DestinationNumber.toString());
	}

	/**
	 * Set value of DestinationNumber
	 * @param destinationnumber
	 */
	public final void setDestinationNumber(java.lang.String destinationnumber)
	{
		setDestinationNumber(getContext(), destinationnumber);
	}

	/**
	 * Set value of DestinationNumber
	 * @param context
	 * @param destinationnumber
	 */
	public final void setDestinationNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destinationnumber)
	{
		getMendixObject().setValue(context, MemberNames.DestinationNumber.toString(), destinationnumber);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sMSParamMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilioconnector.proxies.SMSParam that = (twilioconnector.proxies.SMSParam) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwilioConnector.SMSParam";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
