// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies;

public class Subresource_uris
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subresource_urisMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwilioConnector.Subresource_uris";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Media("Media"),
		Subresource_uris_RootSMSResponse("TwilioConnector.Subresource_uris_RootSMSResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Subresource_uris(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwilioConnector.Subresource_uris"));
	}

	protected Subresource_uris(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subresource_urisMendixObject)
	{
		if (subresource_urisMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwilioConnector.Subresource_uris", subresource_urisMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwilioConnector.Subresource_uris");

		this.subresource_urisMendixObject = subresource_urisMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Subresource_uris.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static twilioconnector.proxies.Subresource_uris initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilioconnector.proxies.Subresource_uris.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twilioconnector.proxies.Subresource_uris initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilioconnector.proxies.Subresource_uris(context, mendixObject);
	}

	public static twilioconnector.proxies.Subresource_uris load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilioconnector.proxies.Subresource_uris.initialize(context, mendixObject);
	}

	public static java.util.List<twilioconnector.proxies.Subresource_uris> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<twilioconnector.proxies.Subresource_uris> result = new java.util.ArrayList<twilioconnector.proxies.Subresource_uris>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TwilioConnector.Subresource_uris" + xpathConstraint))
			result.add(twilioconnector.proxies.Subresource_uris.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Media
	 */
	public final java.lang.String getMedia()
	{
		return getMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of Media
	 */
	public final java.lang.String getMedia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Media.toString());
	}

	/**
	 * Set value of Media
	 * @param media
	 */
	public final void setMedia(java.lang.String media)
	{
		setMedia(getContext(), media);
	}

	/**
	 * Set value of Media
	 * @param context
	 * @param media
	 */
	public final void setMedia(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String media)
	{
		getMendixObject().setValue(context, MemberNames.Media.toString(), media);
	}

	/**
	 * @return value of Subresource_uris_RootSMSResponse
	 */
	public final twilioconnector.proxies.RootSMSResponse getSubresource_uris_RootSMSResponse() throws com.mendix.core.CoreException
	{
		return getSubresource_uris_RootSMSResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Subresource_uris_RootSMSResponse
	 */
	public final twilioconnector.proxies.RootSMSResponse getSubresource_uris_RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twilioconnector.proxies.RootSMSResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString());
		if (identifier != null)
			result = twilioconnector.proxies.RootSMSResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Subresource_uris_RootSMSResponse
	 * @param subresource_uris_rootsmsresponse
	 */
	public final void setSubresource_uris_RootSMSResponse(twilioconnector.proxies.RootSMSResponse subresource_uris_rootsmsresponse)
	{
		setSubresource_uris_RootSMSResponse(getContext(), subresource_uris_rootsmsresponse);
	}

	/**
	 * Set value of Subresource_uris_RootSMSResponse
	 * @param context
	 * @param subresource_uris_rootsmsresponse
	 */
	public final void setSubresource_uris_RootSMSResponse(com.mendix.systemwideinterfaces.core.IContext context, twilioconnector.proxies.RootSMSResponse subresource_uris_rootsmsresponse)
	{
		if (subresource_uris_rootsmsresponse == null)
			getMendixObject().setValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Subresource_uris_RootSMSResponse.toString(), subresource_uris_rootsmsresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subresource_urisMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilioconnector.proxies.Subresource_uris that = (twilioconnector.proxies.Subresource_uris) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwilioConnector.Subresource_uris";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
