// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mfamodule.actions;

import com.mendix.core.Core;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mfamodule.proxies.DatadogLog;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Creates a default datadog log object with the values for IP, useragent etc
 */
public class CreateDatadogLog extends CustomJavaAction<IMendixObject>
{
	public CreateDatadogLog(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		 DatadogLog ddlog = new DatadogLog(getContext());
		if (getContext().getRuntimeRequest().isPresent()) 
		{
			IMxRuntimeRequest request = getContext().getRuntimeRequest().get();
				
			String remoteAddress = request.getRemoteAddr();
			String forwardedFor = request.getHeader("X-Forwarded-For");
			String realIP = request.getHeader("X-Real-IP"); // This is the header which should be used to check the IP address range.	 			
			if( realIP == null )
				realIP = forwardedFor;
			if( realIP == null )
				realIP = remoteAddress;
			
			ddlog.setnetwork_client_ip(realIP);
			
			String useragent = request.getHeader("User-Agent");
			ddlog.sethttp_useragent(useragent);
		}
		
		 
		 return ddlog.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateDatadogLog";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
