// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntocommon.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * param2 and paramName2 are optional (fill empty then)
 * MicroflowToExecute must be the CompleteName (modulename.microflowname)
 */
public class ExecuteUnverifiedMicroflowInOwnTransaction extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject Param;
	private java.lang.String ParamName;
	private IMendixObject Param2;
	private java.lang.String ParamName2;
	private java.lang.String MicroflowToExecute;

	public ExecuteUnverifiedMicroflowInOwnTransaction(IContext context, IMendixObject Param, java.lang.String ParamName, IMendixObject Param2, java.lang.String ParamName2, java.lang.String MicroflowToExecute)
	{
		super(context);
		this.Param = Param;
		this.ParamName = ParamName;
		this.Param2 = Param2;
		this.ParamName2 = ParamName2;
		this.MicroflowToExecute = MicroflowToExecute;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext newContext= this.getContext().getSession().createContext();
		newContext.startTransaction();

		if ( this.Param2 != null && this.ParamName2 != null) 
		{
			Core.microflowCall(this.MicroflowToExecute)
			.withParam(this.ParamName, this.Param)
			.withParam(this.ParamName2, this.Param2)
			.execute(newContext);
		}
		else {
			Core.microflowCall(this.MicroflowToExecute)
			.withParam(this.ParamName, this.Param)
			.execute(newContext);
		}
		newContext.endTransaction();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteUnverifiedMicroflowInOwnTransaction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
