// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntocommon.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Retrieves the object by GUID
 */
public class GetObjectWithId extends CustomJavaAction<IMendixObject>
{
	private java.lang.Long IdOfObject;
	private java.lang.String EntityToReturn;

	public GetObjectWithId(IContext context, java.lang.Long IdOfObject, java.lang.String EntityToReturn)
	{
		super(context);
		this.IdOfObject = IdOfObject;
		this.EntityToReturn = EntityToReturn;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.IdOfObject != 0)
		{
			List<IMendixObject> objects = Core.retrieveXPathQuery(this.getContext(), "//" + EntityToReturn + "[id='"+this.IdOfObject+"']");
			if(objects.size() > 0)
			{
				return objects.get(0);
			}
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObjectWithId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
