// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntocommon.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import approntocommon.proxies.RegexResult;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action performs a regex on a string and sets the group results as an object in a list. On https://regex101.com you can test you regexes. On the right in the Match information you see the Groups 1, 2 etc that will filled in the attributes GroupValue_1, _2 etc of the RegexResult object.
 */
public class GetStringFromRegex extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String Input;
	private java.lang.String Regex;

	public GetStringFromRegex(IContext context, java.lang.String Input, java.lang.String Regex)
	{
		super(context);
		this.Input = Input;
		this.Regex = Regex;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> returnList = new ArrayList<IMendixObject>();
		Matcher m = Pattern.compile(Regex).matcher(Input);
		while (m.find()) {
		    IMendixObject RegexResultRecord = Core.instantiate(getContext(), RegexResult.getType());
		     for (int i = 1; i < m.groupCount()+1 ; i++) {
		    	 RegexResultRecord.setValue(getContext(), "GroupValue_"+ String.valueOf(i), m.group(i));
			}
			returnList.add(RegexResultRecord);
		}
		return returnList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetStringFromRegex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
