// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntocommon.actions;

import java.io.ByteArrayInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class MakeFileEmpty extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __FileToEmpty;
	private system.proxies.FileDocument FileToEmpty;

	public MakeFileEmpty(IContext context, IMendixObject FileToEmpty)
	{
		super(context);
		this.__FileToEmpty = FileToEmpty;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.FileToEmpty = __FileToEmpty == null ? null : system.proxies.FileDocument.initialize(getContext(), __FileToEmpty);

		// BEGIN USER CODE
		 Core.storeFileDocumentContent(getContext(), FileToEmpty.getMendixObject(), FileToEmpty.getName(),  new ByteArrayInputStream("".getBytes("UTF-8")));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MakeFileEmpty";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
