// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntocommon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Default Mendix uses regeular expressions for replacing string (ReplaceFirst and ReplaceAll). This function just do a search and replace without regex features
 */
public class StringSearchReplaceWithoutRegex extends CustomJavaAction<java.lang.String>
{
	private java.lang.String subject;
	private java.lang.String findString;
	private java.lang.String replaceString;

	public StringSearchReplaceWithoutRegex(IContext context, java.lang.String subject, java.lang.String findString, java.lang.String replaceString)
	{
		super(context);
		this.subject = subject;
		this.findString = findString;
		this.replaceString = replaceString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return subject.replace(findString, replaceString);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringSearchReplaceWithoutRegex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
