// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approntocommon.proxies;

public enum NotificationType
{
	Create(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create" }, new java.lang.String[] { "nl_NL", "Nieuw" } }),
	Update(new java.lang.String[][] { new java.lang.String[] { "en_US", "Update" }, new java.lang.String[] { "nl_NL", "Update" } }),
	Cancel(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cancel" }, new java.lang.String[] { "nl_NL", "Annuleren" } }),
	Publish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Publish" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private NotificationType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
