// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package googleauthenticator.actions;

import java.util.concurrent.TimeUnit;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.warrenstrange.googleauth.GoogleAuthenticator;
import com.warrenstrange.googleauth.GoogleAuthenticatorConfig.GoogleAuthenticatorConfigBuilder;

public class IsCodeValid extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String SecretKey;
	private java.lang.String ValidationCode;

	public IsCodeValid(IContext context, java.lang.String SecretKey, java.lang.String ValidationCode)
	{
		super(context);
		this.SecretKey = SecretKey;
		this.ValidationCode = ValidationCode;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		GoogleAuthenticatorConfigBuilder gacb =
                new GoogleAuthenticatorConfigBuilder()
                        .setTimeStepSizeInMillis(TimeUnit.SECONDS.toMillis(30))
                        .setWindowSize(10);
        GoogleAuthenticator ga = new GoogleAuthenticator(gacb.build());

        int validationCodeNr = Integer.parseInt(ValidationCode.replace(" ", ""));
        
        return ga.authorize(this.SecretKey, validationCodeNr);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsCodeValid";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
