// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mfatestmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.webui.CustomJavaAction;
import system.proxies.User;

/**
 * Will evaluate the string value of the MFATestModule constant  "AttibuteNameMFA" and return true or false.
 */
public class HasMFAatribute extends CustomJavaAction<java.lang.Boolean>
{
	public HasMFAatribute(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMetaObject metaObject = Core.getMetaObject(User.entityName);
		for(IMetaObject obj : metaObject.getSubObjects())
		{ 
			for (IMetaPrimitive priv : obj.getMetaPrimitives() ) {
				String mfaAttribute = mfatestmodule.proxies.constants.Constants.getAttributNameMFA();
				if( priv.getName().contentEquals(mfaAttribute))
					return true;
			}
		}
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "HasMFAatribute";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
