// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TwilioConnector module
	public static java.util.Date convertToDateTime(IContext context, java.lang.String _date_created)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("date_created", _date_created);
		return (java.util.Date) Core.microflowCall("TwilioConnector.ConvertToDateTime").withParams(params).execute(context);
	}
	public static java.lang.Long convertToInt(IContext context, java.lang.String _num_segments)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("num_segments", _num_segments);
		return (java.lang.Long) Core.microflowCall("TwilioConnector.ConvertToInt").withParams(params).execute(context);
	}
	public static void createCredential(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("TwilioConnector.CreateCredential").withParams(params).execute(context);
	}
	public static twilioconnector.proxies.SMSParam createSMSParam(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TwilioConnector.CreateSMSParam").withParams(params).execute(context);
		return result == null ? null : twilioconnector.proxies.SMSParam.initialize(context, result);
	}
	public static java.lang.String decrypt(IContext context, java.lang.String _encrypted)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Encrypted", _encrypted);
		return (java.lang.String) Core.microflowCall("TwilioConnector.Decrypt").withParams(params).execute(context);
	}
	public static twilioconnector.proxies.NPCredential decryptCredential(IContext context, twilioconnector.proxies.Credential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("TwilioConnector.DecryptCredential").withParams(params).execute(context);
		return result == null ? null : twilioconnector.proxies.NPCredential.initialize(context, result);
	}
	public static void deleteCredential(IContext context, twilioconnector.proxies.Credential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		Core.microflowCall("TwilioConnector.DeleteCredential").withParams(params).execute(context);
	}
	public static void editCredential(IContext context, twilioconnector.proxies.Credential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		Core.microflowCall("TwilioConnector.EditCredential").withParams(params).execute(context);
	}
	public static java.lang.String encrypt(IContext context, java.lang.String _plain)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Plain", _plain);
		return (java.lang.String) Core.microflowCall("TwilioConnector.Encrypt").withParams(params).execute(context);
	}
	public static void encryptSaveCredential(IContext context, twilioconnector.proxies.NPCredential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		Core.microflowCall("TwilioConnector.EncryptSaveCredential").withParams(params).execute(context);
	}
	public static java.util.List<twilioconnector.proxies.Root_SMSStatus> root_SMSStatus_Get_All(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("TwilioConnector.Root_SMSStatus_Get_All").withParams(params).execute(context);
		java.util.List<twilioconnector.proxies.Root_SMSStatus> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(twilioconnector.proxies.Root_SMSStatus.initialize(context, obj));
		}
		return result;
	}
	public static void root_SMSStatus_Post(IContext context, system.proxies.HttpResponse _httpResponse, twilioconnector.proxies.Root_SMSStatus _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("body", _body == null ? null : _body.getMendixObject());
		Core.microflowCall("TwilioConnector.Root_SMSStatus_Post").withParams(params).execute(context);
	}
	public static boolean sendSMS(IContext context, twilioconnector.proxies.SMSParam _sMSParam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SMSParam", _sMSParam == null ? null : _sMSParam.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("TwilioConnector.SendSMS").withParams(params).execute(context);
	}
	public static boolean sendSMS_SMSCallback(IContext context, twilioconnector.proxies.SMSParam _sMSParam)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SMSParam", _sMSParam == null ? null : _sMSParam.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("TwilioConnector.SendSMS_SMSCallback").withParams(params).execute(context);
	}
}