// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GoogleAuthenticator module
	public static void aCT_2FA_CheckCode(IContext context, googleauthenticator.proxies.GoogleCredentials _googleCredentials)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleCredentials", _googleCredentials == null ? null : _googleCredentials.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.ACT_2FA_CheckCode").withParams(params).execute(context);
	}
	public static void aCT_GoogleCredentials_GenerateSecretKey(IContext context, googleauthenticator.proxies.GoogleCredentials _googleCredentials)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleCredentials", _googleCredentials == null ? null : _googleCredentials.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.ACT_GoogleCredentials_GenerateSecretKey").withParams(params).execute(context);
	}
	public static void aCT_GoogleCredentials_RetrieveAndShowPage(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.ACT_GoogleCredentials_RetrieveAndShowPage").withParams(params).execute(context);
	}
	public static void login_CheckLastLogin_RedirectToCorrectHome(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("GoogleAuthenticator.Login_CheckLastLogin_RedirectToCorrectHome").withParams(params).execute(context);
	}
	public static boolean sUB_CheckLastLogin_WithinAWeek(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("GoogleAuthenticator.SUB_CheckLastLogin_WithinAWeek").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GoogleCredentials_GenerateSecretKey(IContext context, googleauthenticator.proxies.GoogleCredentials _googleCredentials, java.lang.String _issuer, java.lang.String _username)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleCredentials", _googleCredentials == null ? null : _googleCredentials.getMendixObject());
		params.put("Issuer", _issuer);
		params.put("Username", _username);
		return (java.lang.String) Core.microflowCall("GoogleAuthenticator.SUB_GoogleCredentials_GenerateSecretKey").withParams(params).execute(context);
	}
	public static googleauthenticator.proxies.GoogleCredentials sUB_GoogleCredentials_GetOrCreate(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleAuthenticator.SUB_GoogleCredentials_GetOrCreate").withParams(params).execute(context);
		return result == null ? null : googleauthenticator.proxies.GoogleCredentials.initialize(context, result);
	}
}