// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Copies the value to your clipboard
 * @param {string} value
 * @returns {Promise.<void>}
 */
export async function CopyToClipboard(value) {
	// BEGIN USER CODE
	var dummy = document.createElement("textarea");
	document.body.appendChild(dummy);
	dummy.innerHTML = value;
	dummy.select();
	document.execCommand("copy");
	document.body.removeChild(dummy);
	// END USER CODE
}
