// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} classNameToSearch
 * @param {string} classNameToDelete
 * @returns {Promise.<void>}
 */
export async function DeleteClassOnElement(classNameToSearch, classNameToDelete) {
	// BEGIN USER CODE
	if (!classNameToSearch && classNameToSearch.trim() != "") {
		return Promise.reject('classNameToSearch is not set');
	}
	if (!classNameToDelete  && classNameToDelete.trim() != "") {
		return Promise.reject('classNameToDelete is not set');
	}
	return new Promise(function (resolve, reject) {
		var el = document.querySelector('.' + classNameToSearch);
		if (el) {
			el.classList.remove(classNameToDelete);
		}
		resolve();
	})
	// END USER CODE
}
