// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} classNameToSearch
 * @param {string} classNameToCheck
 * @returns {Promise.<boolean>}
 */
export async function HasClassOnElement(classNameToSearch, classNameToCheck) {
	// BEGIN USER CODE
	if (!classNameToSearch && classNameToSearch.trim() != "") {
		return Promise.reject('classNameToSearch is not set');
	}
	if (!classNameToCheck && classNameToCheck.trim() != "") {
		return Promise.reject('classNameToCheck is not set');
	}
	
	var el = document.querySelector('.' + classNameToSearch);
	if(el){
		return Promise.resolve(el.classList.contains(classNameToCheck));
	}
	else{
		return Promise.resolve(false);
	} 
	// END USER CODE
}
