// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} listClassName
 * @returns {Promise.<boolean>}
 */
export async function SelectPreviousListItem(listClassName) {
	// BEGIN USER CODE
	if (!listClassName && listClassName.trim() != "") {
		return Promise.reject('listClassName is not set');
	}
	var el = document.querySelector('.' + listClassName + ' .selected')
	if (el != undefined) {
		if (el.previousElementSibling != undefined) {
			el.previousElementSibling.click();
			return Promise.resolve(true);
		} else {
			el.parentElement.lastElementChild.click();
			return Promise.resolve(true);

		}
	} else {
		return Promise.resolve(false);
	}
	// END USER CODE
}
