// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} inputFieldClassName
 * @param {string} placeholderText
 * @returns {Promise.<void>}
 */
export async function SetPlaceholderOnTextbox(inputFieldClassName, placeholderText) {
	// BEGIN USER CODE
	if (!inputFieldClassName && inputFieldClassName.trim() != "") {
		return Promise.reject('One of the fields is not set');
	}
	if (!placeholderText  && placeholderText.trim() != "") {
		return Promise.reject('Placeholder text is not set');
	}
	return new Promise(function (resolve, reject) {
		var el = document.querySelector('.' + inputFieldClassName + ' input');
		if (el) {
			el.setAttribute("placeholder",placeholderText)
		}
		resolve();
	})
	// END USER CODE
}
