// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Toggle class on parent element of clicked button.
 * @param {string} parentElementClassToSearch
 * @param {string} toggleClassName
 * @returns {Promise.<void>}
 */
export async function ToggleClassOnParentElement(parentElementClassToSearch, toggleClassName) {
	// BEGIN USER CODE
	if (!parentElementClassToSearch && parentElementClassToSearch.trim() != "") {
		return Promise.reject('parentElementClassToSearch is not set');
	}
	if (!toggleClassName && toggleClassName.trim() != "") {
		return Promise.reject('toggleClassName is not set');
	}
	var currentElement = document.activeElement;
	while (!currentElement.classList.contains(parentElementClassToSearch) && currentElement.parentElement) {
		currentElement = currentElement.parentElement;
	}
	if (currentElement.parentElement) {
		var correctParentElement = currentElement.parentElement;
		correctParentElement.classList.toggle(toggleClassName);
	}
	// END USER CODE
}
